language: python
python:
- '3.7'
install:
- pip install --upgrade pip
- pip install pipenv
- pipenv sync --dev
script:
- pytest --cov=./
- codecov
env:
  global:
  - secure: "aR3as+DuZQH/Wteu5a3kuT2FvImo7pHyZ4LTViNsiFrpOT4rCC7ou1vqWbC2zj33JMo1zWKXT+Q4QIl+mmRCqwRNNazjVOlCDn9XxVYPItkCxHJKRK64MXSYetdmH+XnkCcTIzR0/B1l9n/C/tBGOoho+jxkfhQdOJXpFYmK67hZbyxGjW5GgymC7RrnVhVn/udmEz1v0edJqSNKkpi94Wlyj35bPr1dsQRSSU1ai3FTggOcfnSFHzPZO6nN9qF9wE21+tRWk7BzGFIkTj4GVnVupQpTI53UmKKsmYzI2nY34Fkg+2yXJQy3RCUFfC/WuPT0uPEbl1vUuJabqN8U0X/nbfsiUyHIbE5sVZrXzyKAAAgYwDF6f/KJ9XpGaaNqYYKuSMzHba3ZdpcgYnslFhcyd793Zlc/1fuHYLvFy8CyjkOL/QGq5tr0npUQWwUPSF8vsGI4x0MuxMtYTKW7Oy1Qq7UFq6UgTVZtkzFRfJea3RTqvhWsaEmPJ6d+yQmhan2ZF9sMTEIkeUEjE2Zxaeljhm1ZGdDbpMvpt5rV+yASJ2HEOTzgqn3Wmn/7mEyA/s7J0KYH2YsdG4fU+0cG+RAuDeiTFRQ5Tm95dntPG6T9g/WEUcdMJZrqN8m8xru92IbZILRKmOy+Q8dR/wN8j88eP7dgVot+vkuAYNaMoqk="
  - secure: "YSDUgS+oecU5fYNqdxP6eFV9ga2MnCz9BDH5Wm94kGjB+lNbHW0AJlnp2HeYYHGicc3OscCNpV1WVmP41+7wnfWPFmJW7m34yk//yj+FEHC9zCvr1BNEbiocyUHewqpvMTHES6DJR7ePkVvubr5REdIGMlaA8NjHTyzOUTYzq7fIWqosCXKgAcsDCNcCsQ5GEAmrCssWWLdk1/LbCMGYXCH0MYPr8m3qZQu8F/a+rXkQHHFQl2ZddWpKibSAcYL63ihLBM2RiRUk5sSUFQfNkHfJJeSJ/6atG/iaaNNg0eyqt5DQxo/epDgzoKFXniPSy+e+2rejYGWhzj3xe7JO8LE8MNjYiCEYqxmP7eXVbSN6TLdXW3GCRIN0llFWXWn5v8XE9Gikffop7rRVF/rknQxrP4aTqZqyVM36vajNn0TEikCpNNAAgLU40zNQSHb+GQdAsQl1eJTKSJiJsGXuMSxbZ5r8bY3C6jUx6etlIE0d1ebxWeHZVlj+PUFqI/uhzhddGmXiu/6RIxjwUmEg7hPJtH33EZOSs7F2MJ62ZU1LxarM5CPxSC8fT89+7qmKtj6J8QkSfVA7pnj2Uk4Wg90SQ85IToTu+H5RDd2bRr7U1173nAn4opRM+BFvasmEJfC2Vsa9SWnBPuo5LbJf8cWUI6+dP9HCnz934O8UC3E="

deploy:
  provider: pypi
  username: pypatent2018
  distributions: sdist bdist_wheel
  password:
    secure: Rq7O/bXNCsAQVkynntRc49lqeoQ8maLInTuoPCniwCiwluzFeT/tKVsmht/Px41ns0ECVZCmXmt1qpZuBaDTEtLd3p+eMn1ZKjkzEVETNc42GdVrj22fAIJLhGY7DxMpn/2uqCo59XWncp9YKDWskhzTX/aiznQhqL9mq3OxWFpK6cCfRK8CL+4jdybENxLk+ziHwdv3ArR8JyZ5ADvu/WQy71PwWSrLZMrQVqY1Rxus66k0n9JkmxNovVuLYCs894LFvGriJ53dHxbuiZbkDEWxP21KbLl+vj/EslSkgcxOSVgL2we1wo9zuwrELN/SFEUgqB1MD8JkgKz85aOUg+6uOW5SgVA79yx+7GtpNoKvs6wDMHrBndF3QXAB6zZNXSkZi07PH+/SGNku3ltesbXiybZB33gBJ3ZUmTRZv43LCMwS316iOkKkyrKLhCuzmM/pIriB1jVQF8C2d3YQXKRgzyJ1VvOhOmizBGK+1S6EhlX3VUI5y3vUGHHOTrez8DPPRLRqC1VMIwtX9WdodYuTArYoZZ4V/VwAwD0cd6sH5vjlGKtK6xlNkI3+mZr5UPxDzRkv2sKU3k1C9+jwEf0H8OatjGIP1EOVLeUa+jg9CWBZtVdY8DMX6CpUm6LuZ3NroIBq7+F1YPI6ZULeFxU9udxm/x2RgSpksfTmbbI=
