[tool.poetry]
name = "patent_client"
version = "2.2.2"
description = "A set of ORM-style clients for publicly available intellectual property data"
authors = ["Parker Hancock <633163+parkerhancock@users.noreply.github.com>"]
license = "Apache Software License 2.0"

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.9.0"
requests = "^2.28.0"
python-dateutil = "^2.8.2"
requests-cache = "^0.9.4"
marshmallow = "^3.16.0"
xmltodict = "^0.13.0"
PyPDF2 = "^2.2.0"
bs4 = "^0.0.1"
inflection = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
codecov = "^2.1.12"
pytest-cov = "^3.0.0"
pre-commit = "^2.19.0"
pytest-xdist = "^2.5.0"
pandas = "^1.4.2"
mypy = "^0.961"
yankee = {path="../sugar", develop = true}
black = {version = "^22.6.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[scripts]
test = "pytest --basetemp=tmp"
render_docs = "make -f docs/Makefile html"

[tool.pycln]
all = true
