interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Cookie:
      - TS01eb4aff=01874167c711efa9651acdd642c2cd78fd377e233da82ed9f376d88dded7bf61ccd66bbb61611c707ad4cf8906e1af1c18410897c9
      User-Agent:
      - Python Patent Clientbot/3.0.0 (parkerhancock@users.noreply.github.com)
    method: GET
    uri: https://appft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-adv.html&r=0&f=S&l=50&d=PG01&Query=CCL%2F726%2F22+AND+APD%2F19000101-%3E20000619
  response:
    body:
      string: "\n<HTML>\n<HEAD>\n<TITLE>Published Applications Database Search Results:
        CCL/726/22 AND APD/19000101-&gt;20000619 in PGPUB Full-Text Database</TITLE>\n</HEAD>\n<BODY>\n<center>\n<IMG
        SRC=\"/netaicon1/PTO/AppFThdr.gif\">\n</center>\n<center>\n<A HREF=\"/netahtml/PTO/help/help.html\">\n<IMG
        BORDER=\"0\" WIDTH=\"63\" HEIGHT=\"24\" SRC=\"/netaicon1/PTO/help.gif\" ALT=\"[Help]\"></A>\n<a
        href=\"/netahtml/PTO/index.html\">\n<img src=\"/netaicon1/PTO/home.gif\" alt=\"[Home]\"
        border=\"0\" width=\"63\" height=\"24\"></a>\n<a href=\"/netahtml/PTO/search-bool.html\">\n<img
        src=\"/netaicon1/PTO/boolean.gif\" alt=\"[Boolean Search]\" border=\"0\" width=\"63\"
        height=\"24\"></a>\n<A HREF=\"/netahtml/PTO/search-adv.html\">\n<IMG WIDTH=\"63\"
        HEIGHT=\"24\" BORDER=\"0\" SRC=\"/netaicon1/PTO/manual.gif\" ALT=\"[Manual]\"></A>\n<a
        href=\"/netahtml/PTO/srchnum.html\">\n<img src=\"/netaicon1/PTO/number.gif\"
        alt=\"[Number Search]\" border=\"0\" width=\"63\" height=\"24\"></a>\n<A HREF=\"//www.uspto.gov/go/ptcs/\">\n<IMG
        WIDTH=\"63\" HEIGHT=\"24\" BORDER=\"0\" SRC=\"/netaicon1/PTO/copy.gif\" ALT=\"[Order
        Copy]\"></A>\n<A HREF=\"//www.uspto.gov/go/ptdl/\">\n<IMG width=63 height=24
        border=0 SRC=\"/netaicon1/PTO/ptdl.gif\" ALT=\"[PTDLs]\"></A>\n</center>\n<i>Searching
        PGPUB Full-Text Database...</i><BR></p>\n<B>Results of Search in PGPUB Full-Text
        Database db for:<BR> (CCL/726/22 AND APD/19000101-&gt;20000619)</B>: 0 applications.<BR><BR>No
        application publications have matched your query\n<TABLE CELLSPACING=4 CELLPADDING=1>\n<TR>\n<TD
        VALIGN=\"TOP\" ALIGN=\"LEFT\">\n<form action=\"/netacgi/nph-Parser\" method=\"GET\">\n
        \   <INPUT TYPE=\"HIDDEN\" NAME=\"Sect1\" VALUE=\"PTO2\">\n    <INPUT TYPE=\"HIDDEN\"
        NAME=\"Sect2\" VALUE=\"HITOFF\">\n    <INPUT TYPE=\"HIDDEN\" NAME=\"p\" VALUE=\"1\">\n
        \   <INPUT TYPE=\"HIDDEN\" NAME=\"u\" VALUE=\"/netahtml/PTO/search-adv.html\">\n
        \   <INPUT TYPE=\"HIDDEN\" NAME=\"r\" VALUE=\"0\">\n    <INPUT TYPE=\"HIDDEN\"
        NAME=\"f\" VALUE=\"S\">\n    <INPUT TYPE=\"HIDDEN\" NAME=\"l\" VALUE=\"50\">\n<INPUT
        type=\"hidden\" name=\"d\" value=\"PG01\">\n<INPUT type=\"submit\" value=\"Refine
        Search\">\n</TD>\n<TD VALIGN=\"TOP\" ALIGN=\"LEFT\" COLSPAN=4>\n<INPUT size=50
        name=\"Query\" value=\"CCL/726/22 AND APD/19000101-&gt;20000619\">\n</TD>\n</FORM>\n</TR>\n</TABLE>\n</BODY></HTML>"
    headers:
      Content-Type:
      - text/html
      Set-Cookie:
      - TS01eb4aff=01874167c711efa9651acdd642c2cd78fd377e233da82ed9f376d88dded7bf61ccd66bbb61611c707ad4cf8906e1af1c18410897c9;
        Path=/; Domain=.appft.uspto.gov
      Strict-Transport-Security:
      - max-age=31536000
      Transfer-Encoding:
      - chunked
    status:
      code: 200
      message: Script results follow
version: 1
